### ISSUE TITLE
Connection recovery exception

### ISSUE THREAD

**Issue by erez-rabih** [michaelklishin/langohr#87]
Hi,

A few days ago we had a rabbitmq failure. This happened before and all connections/topologies were restarted as expected. A few days ago something else happened - we saw this stacktrace:
```
Caught an exception during connection recovery!
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.rabbitmq.client.impl.FrameHandlerFactory.create(FrameHandlerFactory.java:32)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:34)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverConnection(AutorecoveringConnection.java:476)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:444)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$1.shutdownCompleted(AutorecoveringConnection.java:383)
	at com.rabbitmq.client.impl.ShutdownNotifierComponent.notifyListeners(ShutdownNotifierComponent.java:75)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:578)
	at java.lang.Thread.run(Thread.java:745)
Caught an exception during connection recovery!
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.rabbitmq.client.impl.FrameHandlerFactory.create(FrameHandlerFactory.java:32)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:34)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverConnection(AutorecoveringConnection.java:476)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:444)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$1.shutdownCompleted(AutorecoveringConnection.java:383)
	at com.rabbitmq.client.impl.ShutdownNotifierComponent.notifyListeners(ShutdownNotifierComponent.java:75)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:578)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "async-dispatch-3" com.rabbitmq.client.AlreadyClosedException: connection is already closed due to connection error; cause: com.rabbitmq.client.MissedHeartbeatException: Heartbeat missing with heartbeat = 10 seconds
	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:195)
	at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:309)
	at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:657)
	at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:640)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicPublish(AutorecoveringChannel.java:172)
	at langohr.basic$publish.invoke(basic.clj:113)
	at langohr.basic$publish.invoke(basic.clj:91)
	at stimulus.rabbit$publisher$fn__16262$state_machine__5069__auto____16263$fn__16265.invoke(rabbit.clj:26)
	at stimulus.rabbit$publisher$fn__16262$state_machine__5069__auto____16263.invoke(rabbit.clj:26)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:1012)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:1016)
	at clojure.core.async.impl.ioc_macros$take_BANG_$fn__5085.invoke(ioc_macros.clj:1025)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__1383.invoke(channels.clj:135)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
And the process went stale.
We did not define any manual recovery logic.
How can we make sure this doesn't happen again?
Thanks!

**Comment by michaelklishin** [comment]
This client cannot avoid socket exceptions. You haven't provided much info on the version used but I recall a set of similar issues reported for the Java client 3.6.x up to 3.6.6. We'll soon move to the 4.0.2 (once it is out).

**Comment by erez-rabih** [comment]
@michaelklishin Thanks for the fast response.
Why can't we try/catch exceptions on the automatic recovery procedure?

**Comment by michaelklishin** [comment]
@erez-rabih you can. It's called "doing recovery on your own."

**Comment by erez-rabih** [comment]
@michaelklishin would you consider a pull request for fixing this issue on automatic recovery?

**Comment by michaelklishin** [comment]
@erez-rabih what would you do after catching a socket timeout exception? Make the client retry? It should already do that. How would you make the client work if the user can intervene and do the same thing? I have no answer to this so either rely on the default recovery sequence (which should retry on this particular exception) or do 100% of the recovery work yourself.

**Comment by erez-rabih** [comment]
@michaelklishin Something like exponential backoff sounds reasonable.
Definitely won't let the thread go stale...

**Comment by michaelklishin** [comment]
@erez-rabih this client relies on the Java client for recovery. I (and team RabbitMQ) would consider a PR for it if you are sure you understand what the issue is. There is no specific information provided beyond

 * A stack trace that mentions a socket timeout
 * "the process went stale"

and it's not enough to reason about what exactly stalled the retries.

**Comment by michaelklishin** [comment]
@erez-rabih this client retries at fixed intervals by design. Exponential back-off is awesome unless you have to debug it. So there are no plans to switch the Java client to use exponential back-off.

In any case, the problem is not with fixed interval or exponential back-off retries. The problem is that at some point retries stop on an exception that should be retried. That's another important factor to consider: there are exceptions that the client may or may want to retry on. So it's way more involved than just suggesting that the client should use exponential back-off.

FWIW this design has been around for some 5 years (introduced in amqp gem around 2011), present in multiple clients in pretty different languages, and I am yet to see a major flaw in it. Every issue I've seen is an implementation detail or something that a library cannot entirely solve (like concurrent user actions interfering with recovery).

**Comment by erez-rabih** [comment]
@michaelklishin Thanks for explaining I understand.

I thought that there was a missing try/catch somewhere and that's the reason the process went stale.
You say that it should have tried reconnecting indefinitely and if that's the case I should investigate more in order to figure why the retry loop halted.

If I have more findings I will post them here and re-open the issue.

**Comment by michaelklishin** [comment]
@erez-rabih that was a long way of saying: your understanding of the problem is very simplistic. I'm sorry but making suggestions without gathering more data and a having way to reproduce (this particular exception can be triggered with a firewall rule introduced mid-recovery) is not going to get you far.

**Comment by michaelklishin** [comment]
@erez-rabih let me just say that `java.net.SocketTimeoutException` is a subclass of `java.io.IOException` which is the first exception most JVM developers would test against.
